{"domain":".idmsa.apple.com","httpOnly":true,"name":"aa","path":"/","secure":true,"value":"4BDF005E4B5AAAFD55651A6CB58AF35F"}
{"domain":"idmsa.apple.com","httpOnly":true,"name":"JSESSIONID","path":"/","secure":true,"value":"B1E14DAADDE3C7436120BAF8550D1048"}
{"domain":".apple.com","httpOnly":true,"name":"site","path":"/","secure":true,"value":"USA"}
{"domain":".apple.com","expiry":1603371402.575876,"httpOnly":false,"name":"xp_ab","path":"/","secure":true,"value":"1#WqjkRLH+-2+A7h2ykc2#isj11bm+-2+DlYcSJw1"}
{"domain":".apple.com","expiry":1603371402.575828,"httpOnly":false,"name":"xp_ci","path":"/","secure":true,"value":"3z1fNtmMzA8pz4gbz9DkzokN3Gs5a"}
{"domain":".apple.com","httpOnly":true,"name":"dslang","path":"/","secure":true,"value":"US-EN"}
{"domain":".apple.com","httpOnly":false,"name":"geo","path":"/","secure":false,"value":"US"}
{"domain":".apple.com","expiry":1603371402.575888,"httpOnly":false,"name":"xp_abc","path":"/","secure":true,"value":"A7h2ykc2#DlYcSJw1"}
{"domain":".apple.com","httpOnly":false,"name":"ccl","path":"/","secure":false,"value":"0Hr325TTiAapymbWGjz+W1Fr+pndLT9z"}
