{"domain":".idmsa.apple.com","httpOnly":true,"name":"aa","path":"/","secure":true,"value":"AD15C8A3D9B8EA2885B5F837F0B7EDAB"}
{"domain":"idmsa.apple.com","httpOnly":true,"name":"JSESSIONID","path":"/","secure":true,"value":"FDCC71B7050D1745F3F21932C0FB509D"}
{"domain":".apple.com","httpOnly":true,"name":"site","path":"/","secure":true,"value":"USA"}
{"domain":".apple.com","expiry":1603367917.955479,"httpOnly":false,"name":"xp_ab","path":"/","secure":true,"value":"1#WqjkRLH+-2+A7h2ykc0"}
{"domain":".apple.com","expiry":1603367917.95543,"httpOnly":false,"name":"xp_ci","path":"/","secure":true,"value":"3z1ydN65zGZz4bnzCnyzOTDOudLa"}
{"domain":".apple.com","httpOnly":true,"name":"dslang","path":"/","secure":true,"value":"US-EN"}
{"domain":".apple.com","httpOnly":false,"name":"geo","path":"/","secure":false,"value":"US"}
{"domain":".apple.com","expiry":1603367917.955491,"httpOnly":false,"name":"xp_abc","path":"/","secure":true,"value":"A7h2ykc0"}
{"domain":".apple.com","httpOnly":false,"name":"ccl","path":"/","secure":false,"value":"L5cwZC8ZbBPunvZmHb+IdA6IHEomgOBM"}
