{"domain":".idmsa.apple.com","httpOnly":true,"name":"aa","path":"/","secure":true,"value":"44FDFE6CBFF2C6A11BD6170A28D052F6"}
{"domain":"idmsa.apple.com","httpOnly":true,"name":"JSESSIONID","path":"/","secure":true,"value":"E7545EBF10931A5267BE032D9CE18CF0"}
{"domain":".apple.com","httpOnly":true,"name":"site","path":"/","secure":true,"value":"USA"}
{"domain":".apple.com","expiry":1603357074.403789,"httpOnly":false,"name":"xp_ab","path":"/","secure":true,"value":"1#WqjkRLH+-2+A7h2ykc2"}
{"domain":".apple.com","expiry":1603357074.40374,"httpOnly":false,"name":"xp_ci","path":"/","secure":true,"value":"3z4bXsGAzDFxz5FpzAr8zHTn5DIgc"}
{"domain":".apple.com","httpOnly":true,"name":"dslang","path":"/","secure":true,"value":"US-EN"}
{"domain":".apple.com","httpOnly":false,"name":"geo","path":"/","secure":false,"value":"US"}
{"domain":".apple.com","expiry":1603357074.403801,"httpOnly":false,"name":"xp_abc","path":"/","secure":true,"value":"A7h2ykc2"}
{"domain":".apple.com","httpOnly":false,"name":"ccl","path":"/","secure":false,"value":"5hUqpuafMuHhf3rrceoUwAxFBMDBJYOo"}
